Repository Yoast/wpseo-woocommerce, pull requests merged in 2018-08, with the labels that each got.

#244 Automaticaly push files to dist repository when a new tag is committed
  .travis.yml
  deploy_keys/wpseo_woo_deploy.enc
  scripts/deploy_to_dist.sh
  tools/grunt/config/aliases.yaml
Labels: in progress

#269 Add WC plugin headers
  wpseo-woocommerce.php
Labels: in progress

#268 Fix broken grunt configurations
  js/yoastseo-woo-plugin-800.js
  js/yoastseo-woo-plugin-800.min.js
  js/yoastseo-woo-replacevars-800.js
  js/yoastseo-woo-replacevars-800.min.js
  languages/yoast-woo-seo.pot
  tools/grunt/config/aliases.yaml
  tools/grunt/config/clean.js
  tools/grunt/config/shell.js
  tools/webpack/webpack.config.prod.js
Labels: code-review

#271 Fixed configuration files for building artifacts
  tools/grunt/config/aliases.yaml
  tools/grunt/config/compress.js
  tools/grunt/config/copy.js
Labels: code-review

#270 Adapt custom assessment for web worker
  Gruntfile.js
  js/src/assessments/ProductDescriptionAssessment.js
  js/src/yoastseo-woo-plugin.js
  js/src/yoastseo-woo-worker.js
  js/yoast-woocommerce-seo-plugin-790.min.js.map
  js/yoastseo-woo-plugin-790.min.js.map
  js/yoastseo-woo-plugin-81-RC2.js
  js/yoastseo-woo-plugin-81-RC2.min.js
  js/yoastseo-woo-replacevars-790.min.js.map
  js/yoastseo-woo-replacevars-81-RC2.js
  js/yoastseo-woo-replacevars-81-RC2.min.js
  js/yoastseo-woo-worker-81-RC2.js
  js/yoastseo-woo-worker-81-RC2.min.js
  package.json
  tools/grunt/config/clean.js
  tools/grunt/config/eslint.js
  tools/grunt/config/shell.js
  tools/grunt/config/watch.js
  tools/webpack/webpack.config.default.js
  wpseo-woocommerce.php
Labels: in progress

#272 Bump Yoast SEO minimal version requirement to 8.1
  tests/woocommerce-seo-test.php
  wpseo-woocommerce.php
Labels: code-review, in progress

#273 PHPCS: Update to use YoastCS 1.0 / WPCS 1.0
  .phpcs.xml.dist
  classes/option-woo.php
  composer.json
  composer.lock
  tests/doubles/option-woo-double.php
  tests/framework/woocommerce-unittestcase.php
  wpseo-woocommerce.php
Labels: in progress, needs-code-review
