Repository Yoast/wpseo-woocommerce, pull requests merged in 2018-05, with the labels that each got.

#247 Bump YoastSEO.js to 1.31
  package.json
  yarn.lock
Labels: needs-code-review

#248 update product name
  wpseo-woocommerce.php
Labels: needs-code-review

#249 Exclude artifact folder from pot file creation
  grunt/config/makepot.js
  languages/yoast-woo-seo.pot
Labels: bug, in progress

#253 Bump YoastSEO.js to 1.33.1
  package.json
  yarn.lock
Labels: in progress, needs-code-review

#255 Travis: Composer efficiency improvements
  .travis.yml
Labels: acceptance
