Repository Yoast/wpseo-woocommerce, pull requests merged in 2018-06, with the labels that each got.

#256 CS: Update PHPCS ruleset and composer.lock for PHPCS 3.3.0
  .phpcs.xml.dist
  composer.lock
Labels: needs-acceptance

#257 Bump YoastSEO.js to 1.34.0
  js/src/yoastseo-woo-replacevars.js
  package.json
  yarn.lock
Labels: in progress

#258 Implement filter for the recommended replacevars.
  wpseo-woocommerce.php
Labels: in progress, needs-code-review ★

#260 Excludes the WooCommerce core pages from the sitemap
  wpseo-woocommerce.php
Labels: in progress

#262 Introduce the use of the Yoast grunt tasks plugin
  Gruntfile.js
  grunt/custom/set-version.js
  grunt/custom/update-version.js
  package.json
  yarn.lock
Labels: in progress
