Repository Yoast/wpseo-woocommerce, pull requests merged in 2019-12, with the labels that each got.

#446 Composer: update BrainMonkey dependency
  composer.json
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#447 Bump plugin grunt tasks
  js/yoastseo-woo-plugin-1240.js
  js/yoastseo-woo-plugin-1240.min.js
  js/yoastseo-woo-replacevars-1240.js
  js/yoastseo-woo-replacevars-1240.min.js
  js/yoastseo-woo-worker-1240.js
  js/yoastseo-woo-worker-1240.min.js
  languages/yoast-woo-seo.pot
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#451 PHPCS: Update to YoastCS 2.0.0
  .phpcs.xml.dist
  .travis.yml
  classes/option-woo.php
  classes/woocommerce-schema.php
  composer.json
  composer.lock
  integration-tests/bootstrap.php
  integration-tests/classes/option-woo-test.php
  integration-tests/woocommerce-seo-test.php
  tests/TestCase.php
  wpseo-woocommerce.php
Labels: changelog: other, yoast cs/qa
