Repository Yoast/wpseo-woocommerce, pull requests merged in 2019-11, with the labels that each got.

#427 Update Mockery for testing on PHP 7.4
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#435 Remove all hidden products from XML sitemap
  wpseo-woocommerce.php
Labels: changelog: bugfix

#426 Tests: fix compatibility with PHP 7.4
  integration-tests/woocommerce-seo-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#433 Stop explicit support for PHP < 5.6 / WP < 5.2
  .travis.yml
  README.md
  composer.json
  composer.lock
  integration-tests/bootstrap.php
  wpseo-woocommerce.php
Labels: changelog: non-user-facing, yoast cs/qa

#439 Prepare for indexables
  classes/woocommerce-schema.php
Labels: 1, changelog: non-user-facing, type: development

#443 Set minimum WP version to 5.2 and minimum YoastSEO version to 12.6
  integration-tests/woocommerce-seo-test.php
  wpseo-woocommerce.php
Labels: changelog: other

#440 Travis: don't allow builds against PHP 7.4 to fail
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa
