Repository Yoast/wpseo-woocommerce, pull requests merged in 2019-10, with the labels that each got.

#413 CS: enforce consistent array format
  .phpcs.xml.dist
Labels: changelog: non-user-facing, yoast cs/qa

#414 Travis: minor tweak
  .travis.yml
Labels: yoast cs/qa

#419 CS: use the correct namespace name
  tests/TestCase.php
  tests/classes/schema-test.php
  tests/doubles/schema-double.php
Labels: changelog: non-user-facing, yoast cs/qa

#420 PHPUnit bootstrap: fix typo
  tests/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#421 PHPUnit bootstrap: friendly error message
  tests/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#422 PHPUnit: use most specific assertion
  tests/classes/schema-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#423 Tidy up PHPUnit config files
  phpunit-integration.xml.dist
  phpunit.xml.dist
Labels: changelog: non-user-facing, yoast cs/qa

#424 PHPUnit: make (new) unit tests compatible with higher PHPUnit versions
  tests/TestCase.php
Labels: changelog: non-user-facing, yoast cs/qa

#425 Set tested up to to 5.3, minimum wp to 5.2 and PHP to 5.6.20
  README.md
Labels: changelog: other
