Repository Yoast/wpseo-woocommerce, pull requests merged in 2019-03, with the labels that each got.

#331 Remove the deprecated function
  wpseo-woocommerce.php
Labels: in progress

#311 Change `og:brand` to `product:brand`
  wpseo-woocommerce.php
Labels: has patch

#318 Travis: test builds against PHP 7.4
  .travis.yml
Labels: yoast cs/qa

#325 Travis: improve dependency security check
  .travis.yml
  composer.json
  composer.lock
Labels: yoast cs/qa
