Repository Yoast/wpseo-woocommerce, pull requests merged in 2020-03, with the labels that each got.

#538 Fix unit test
  tests/classes/schema-test.php
Labels: changelog: non-user-facing

#537 Update the PR template to also ask for context
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog: non-user-facing

#532 Add color property to the product schema output.
  classes/option-woo.php
  classes/woocommerce-schema.php
  classes/woocommerce-seo.php
  integration-tests/classes/option-woo-test.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#539 Add replacement variables for product global identifiers
  classes/woocommerce-seo.php
  js/src/yoastseo-woo-replacevars.js
  tests/classes/schema-test.php
Labels: changelog: enhancement

#549 Set WC tested up to version to 4.0
  wpseo-woocommerce.php
Labels: changelog: other

#551 Fixes `test_change_product_with_color` Schema tests on trunk
  tests/classes/schema-test.php
Labels: changelog: non-user-facing

#530 Output priceValidUntil for products on sale with a set sale end date
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: bugfix

#544 Improve Open Graph product availability
  classes/woocommerce-opengraph.php
  tests/classes/opengraph-test.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#546 Add term hierarchy as replacement variable.
  classes/woocommerce-seo.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#556 Improve the output of the price replacement variable
  classes/woocommerce-seo.php
  js/src/yoastseo-woo-replacevars.js
Labels: changelog: enhancement

#553 Implemented full image from gallery in xml sitemap
  classes/woocommerce-seo.php
Labels: changelog: bugfix

#561 Check offers data exist before attempting to use it.
  classes/woocommerce-schema.php
Labels: changelog: bugfix
