Repository Yoast/wpseo-woocommerce, pull requests merged in 2020-02, with the labels that each got.

#511 Show all taxonomies in Brands & Manufacturer dropdowns
  classes/woocommerce-seo.php
Labels: changelog: bugfix

#512 12.5.1 fix to trunk
  classes/woocommerce-seo.php
Labels: changelog: non-user-facing

#513 Add explanatory copy above product identifiers
  classes/woocommerce-yoast-tab.php
Labels: changelog: enhancement

#517 CS: clean up after merges
  classes/woocommerce-utils.php
  classes/woocommerce-yoast-tab.php
  tests/classes/schema-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#518 QA: use FQN function calls in namespaced files
  tests/classes/opengraph-test.php
  tests/classes/schema-test.php
  tests/classes/utils-test.php
  tests/classes/woocommerce-dependencies-test.php
  tests/classes/woocommerce-yoast-tab-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#520 Update YoastCS and dependencies
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#519 QA: consistent use of `use` statements
  tests/classes/woocommerce-yoast-tab-test.php
  tests/doubles/opengraph-double.php
Labels: changelog: non-user-facing, yoast cs/qa

#521 QA: declare static closures as static
  tests/classes/opengraph-test.php
  tests/classes/schema-test.php
  tests/classes/utils-test.php
  tests/classes/woocommerce-yoast-tab-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#522 QA: use the most specific test assertion
  tests/classes/opengraph-test.php
  tests/classes/schema-test.php
  tests/classes/utils-test.php
  tests/classes/woocommerce-yoast-tab-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#523 Fix missing Premium functionality
  js/src/yoastseo-woo-handle-excerpt-editors.js
  js/src/yoastseo-woo-plugin.js
Labels: changelog: bugfix

#528 Use surface for getting value
  classes/woocommerce-opengraph.php
  classes/woocommerce-schema.php
Labels: changelog: non-user-facing

#531 valueAddedTaxIncluded is not set to false when prices are added including tax
  classes/woocommerce-schema.php
  classes/woocommerce-utils.php
  tests/classes/schema-test.php
Labels: changelog: bugfix

#534 Fix tax schema woocommerce
  classes/option-woo.php
  classes/woocommerce-schema.php
  classes/woocommerce-seo.php
  classes/woocommerce-utils.php
  tests/classes/opengraph-test.php
  tests/classes/schema-test.php
  tests/classes/utils-test.php
Labels: changelog: bugfix
