Repository Yoast/wpseo-woocommerce, pull requests merged in 2020-05, with the labels that each got.

#596 Don't show open graph images gallery when image set by user
  classes/woocommerce-opengraph.php
  tests/classes/opengraph-test.php
Labels: changelog: bugfix

#597 Twitter image falls back to first image in product image gallery
  classes/woocommerce-seo.php
  classes/woocommerce-twitter.php
  tests/classes/twitter-test.php
Labels: changelog: bugfix

#598 Fix getting name on null term
  classes/woocommerce-schema.php
Labels: changelog: non-user-facing

#602 Composer: update CS dependencies
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#603 QA: remove unused variable
  tests/classes/twitter-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#604 QA: don't use FQN for an imported class
  tests/classes/opengraph-test.php
  tests/classes/twitter-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#605 CS: minor fixes
  classes/woocommerce-schema.php
  tests/classes/presenters/product-price-amount-presenter-test.php
  tests/classes/presenters/product-price-currency-presenter-test.php
  tests/mocks/schema-ids.php
Labels: changelog: non-user-facing, yoast cs/qa

#601 Bug: fix undefined variable notice
  classes/woocommerce-schema.php
Labels: 0, bug, changelog: bugfix

#610 Call the right class
  classes/woocommerce-permalink-watcher.php
Labels: 0, changelog: bugfix

#608 Sku incorrect value to blank
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
  tests/doubles/schema-double.php
Labels: changelog: bugfix

#607 Alter schema availability for products on backorder.
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#612 P3-14 Added a single test for using the valueAddedTaxIncluded property
  tests/classes/schema-test.php
Labels: changelog: non-user-facing
