Repository Yoast/wpseo-woocommerce, pull requests merged in 2020-07, with the labels that each got.

#617 PHPCS: enable caching between runs
  .cache/.gitkeep
  .gitattributes
  .gitignore
  .phpcs.xml.dist
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#620 Upgrade plugin grunt tasks
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#625 Travis now clones the distribution version of WordPress SEO
  .travis.yml
Labels: changelog: non-user-facing

#618 Travis/Composer: switch over to parallel linting of PHP files
  .travis.yml
  composer.json
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#623 Update checkbox to new styling
  classes/woocommerce-seo.php
Labels: UI change

#627 Travis: change from "trusty" to "xenial"
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa
