Repository Yoast/wpseo-woocommerce, pull requests merged in 2020-08, with the labels that each got.

#629 Set minimum WP version to 5.4 and tested up to to 5.5
  .travis.yml
  README.md
Labels: changelog: other

#630 Enable tracking on plugin activation.
  classes/woocommerce-seo.php
  wpseo-woocommerce.php
Labels: changelog: other

#631 Add webpage type to types
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: bugfix

#633 [QAK-2167] Check if WPSEO_Options exists before calling one of its methods
  classes/woocommerce-seo.php
Labels: changelog: non-user-facing

#634 Up WC tested up to to 4.5.0
  wpseo-woocommerce.php
Labels: changelog: non-user-facing
