Repository Yoast/wpseo-woocommerce, pull requests merged in 2020-01, with the labels that each got.

#452 Integrate with options framework
  classes/option-woo.php
  classes/woocommerce-schema.php
  classes/woocommerce-wrappers.php
  integration-tests/classes/option-woo-test.php
  integration-tests/doubles/option-woo-double.php
  integration-tests/woocommerce-seo-test.php
  tests/classes/schema-test.php
  wpseo-woocommerce.php
Labels: changelog: non-user-facing

#455 Filters the retrieved taxonomies to only have the viewable ones.
  wpseo-woocommerce.php
Labels: bug, changelog: bugfix, has patch

#436 Retrieves noindex from shop page instead of product archive
  wpseo-woocommerce.php
Labels: changelog: bugfix, community-patch

#459 Remove class Yoast_Product_WPSEO_WooCommerce
  classes/product-wpseo-woocommerce.php
Labels: changelog: non-user-facing

#470 Implement @hansjovis suggestions for lodash
  package.json
  tools/webpack/webpack.config.default.js
  yarn.lock
Labels: changelog: non-user-facing

#467 Fix a notice for empty image
  classes/woocommerce-schema.php
Labels: changelog: bugfix

#468 Enhance Schema review output
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#472 Remove distribution files from repository
  .gitignore
  Gruntfile.js
  js/yoastseo-woo-plugin-1241.js
  js/yoastseo-woo-plugin-1241.min.js
  js/yoastseo-woo-replacevars-1241.js
  js/yoastseo-woo-replacevars-1241.min.js
  js/yoastseo-woo-worker-1241.js
  js/yoastseo-woo-worker-1241.min.js
  package.json
  tools/grunt/config/clean.js
  tools/webpack/webpack.config.default.js
  tools/webpack/webpack.config.dev.js
  wpseo-woocommerce.php
Labels: changelog: non-user-facing, needs-pair

#473 Make sure we analyze the excerpt content too
  js/src/yoastseo-woo-plugin.js
  js/yoastseo-woo-plugin-1241.js
  js/yoastseo-woo-plugin-1241.min.js
  yarn.lock
Labels: changelog: enhancement

#463 If the shop page isn't set in Woo, don't try to use it in the XML sitemap
  wpseo-woocommerce.php
Labels: changelog: enhancement

#457 Adds SKU to the output, fixes instock to be in stock
  wpseo-woocommerce.php
Labels: changelog: enhancement

#464 When Organization isn't set, don't use it in our Schema output.
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: bugfix

#462 Use primary term for brand in OG output when available
  wpseo-woocommerce.php
Labels: changelog: enhancement

#460 Add productID to Schema output
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#461 Add product:condition to our OG output
  wpseo-woocommerce.php
Labels: changelog: enhancement

#465 Improve Schema for offers
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#471 Throw a warning when WooCommerce is not active
  Gruntfile.js
  classes/woocommerce-dependencies.php
  classes/woocommerce-seo.php
  integration-tests/woocommerce-seo-test.php
  languages/yoast-woo-seo.pot
  tests/classes/woocommerce-dependencies-test.php
  tests/doubles/woocommerce-dependencies-double.php
  wpseo-woocommerce.php
Labels: changelog: enhancement

#474 Travis: use 7.4 not snapshot
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#475 QA: remove unnecessary `else` control structure
  classes/option-woo.php
Labels: changelog: non-user-facing, yoast cs/qa

#476 Modernize: use `__DIR__` instead of `dirname( __FILE__ )`
  integration-tests/bootstrap.php
  wpseo-woocommerce.php
Labels: changelog: non-user-facing, yoast cs/qa

#477 QA: remove useless variable
  classes/woocommerce-seo.php
Labels: changelog: non-user-facing, yoast cs/qa

#478 QA: remove unused use statements
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#479 QA: add missing `use` statement for Mockery
  tests/TestCase.php
Labels: changelog: non-user-facing, yoast cs/qa

#480 QA: use FQN functions in namespaced files
  tests/TestCase.php
  tests/classes/schema-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#481 QA: declare static closures as static
  tests/TestCase.php
Labels: changelog: non-user-facing, yoast cs/qa

#482 Docs: various improvements
  classes/option-woo.php
  classes/woocommerce-schema.php
  classes/woocommerce-seo.php
  integration-tests/classes/option-woo-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#483 Improve tests for Schema and Dependencies code
  classes/woocommerce-dependencies.php
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
  tests/classes/woocommerce-dependencies-test.php
  tests/doubles/schema-double.php
  tests/doubles/woocommerce-dependencies-double.php
  wpseo-woocommerce.php
Labels: changelog: non-user-facing

#486 Remove type hint and add typecheck
  wpseo-woocommerce.php
Labels: changelog: non-user-facing

#488 Don't exclude product attributes from the XML sitemap by default
  classes/woocommerce-seo.php
Labels: changelog: bugfix

#490 Add option to display the price in Schema and OpenGraph with tax included
  classes/option-woo.php
  classes/woocommerce-opengraph.php
  classes/woocommerce-schema.php
  classes/woocommerce-seo.php
  classes/woocommerce-utils.php
  tests/classes/opengraph-test.php
  tests/classes/schema-test.php
  tests/classes/utils-test.php
  tests/doubles/opengraph-double.php
Labels: changelog: enhancement

#492 Properly clean descriptions
  classes/woocommerce-seo.php
Labels: changelog: bugfix

#504 Don't output empty retailer_item_id
  classes/woocommerce-seo.php
Labels: changelog: bugfix

#503 Allow saving empty value for GTIN etc.
  classes/woocommerce-schema.php
  classes/woocommerce-yoast-tab.php
  tests/classes/woocommerce-yoast-tab-test.php
Labels: changelog: non-user-facing
