Repository Yoast/wpseo-woocommerce, pull requests merged in 2020-04, with the labels that each got.

#570 Set minimum WP version to 5.3
  README.md
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#572 Composer: update YoastCS to v 2.0.2
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#573 Docs: various tweaks
  classes/woocommerce-opengraph.php
  classes/woocommerce-schema.php
  classes/woocommerce-utils.php
  tests/classes/permalink-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#574 CS: boolean operator at the start of the line in multi-line conditions
  classes/woocommerce-utils.php
Labels: changelog: non-user-facing, yoast cs/qa

#575 QA: add missing import `use` statements for classes
  tests/classes/permalink-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#568 Bring back product metatags
  classes/presenters/woocommerce-abstract-product-availability-presenter.php
  classes/presenters/woocommerce-abstract-product-presenter.php
  classes/presenters/woocommerce-pinterest-product-availability-presenter.php
  classes/presenters/woocommerce-product-availability-presenter.php
  classes/presenters/woocommerce-product-brand-presenter.php
  classes/presenters/woocommerce-product-condition-presenter.php
  classes/presenters/woocommerce-product-opengraph-deprecation-presenter.php
  classes/presenters/woocommerce-product-price-amount-presenter.php
  classes/presenters/woocommerce-product-price-currency-presenter.php
  classes/presenters/woocommerce-product-retailer-item-id-presenter.php
  classes/woocommerce-opengraph.php
  classes/woocommerce-schema.php
  classes/woocommerce-seo.php
  tests/classes/opengraph-test.php
Labels: changelog: non-user-facing

#576 QA: use the variable
  classes/woocommerce-schema.php
Labels: changelog: non-user-facing, yoast cs/qa

#578 Hide all Yoast columns in the Product overview page except the SEO Score column
  classes/option-woo.php
  classes/woocommerce-seo.php
  integration-tests/classes/option-woo-test.php
  integration-tests/woocommerce-seo-test.php
Labels: changelog: enhancement

#567 Escape Attribute term
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: bugfix

#588 Fix several issues
  classes/presenters/woocommerce-product-price-amount-presenter.php
  classes/presenters/woocommerce-product-price-currency-presenter.php
  classes/presenters/woocommerce-product-retailer-item-id-presenter.php
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
  tests/classes/seo-trait.php
  tests/doubles/schema-double.php
  tests/mocks/schema-ids.php
Labels: changelog: non-user-facing

#591 Fix OpenGraph deprecations
  classes/woocommerce-opengraph.php
  tests/classes/opengraph-test.php
  tests/doubles/opengraph-double.php
Labels: 0.5, changelog: non-user-facing

#590 Removal of the use statements
  classes/presenters/woocommerce-abstract-product-presenter.php
  classes/presenters/woocommerce-pinterest-product-availability-presenter.php
  classes/presenters/woocommerce-product-availability-presenter.php
  classes/presenters/woocommerce-product-brand-presenter.php
  classes/presenters/woocommerce-product-condition-presenter.php
  classes/presenters/woocommerce-product-opengraph-deprecation-presenter.php
  classes/presenters/woocommerce-product-price-amount-presenter.php
  classes/presenters/woocommerce-product-price-currency-presenter.php
  classes/presenters/woocommerce-product-retailer-item-id-presenter.php
Labels: 0, changelog: non-user-facing

#592 Remove OpenGraph description override
  classes/woocommerce-opengraph.php
  tests/classes/opengraph-test.php
Labels: changelog: enhancement

#593 Add presenter tests
  .phpcs.xml.dist
  classes/presenters/woocommerce-product-opengraph-deprecation-presenter.php
  tests/classes/presenters/pinterest-product-availability-presenter-test.php
  tests/classes/presenters/product-availability-presenter-test.php
  tests/classes/presenters/product-brand-presenter-test.php
  tests/classes/presenters/product-condition-presenter-test.php
  tests/classes/presenters/product-opengraph-deprecation-presenter-test.php
  tests/classes/presenters/product-price-amount-presenter-test.php
  tests/classes/presenters/product-price-currency-presenter-test.php
  tests/classes/presenters/product-retailer-item-id-presenter-test.php
Labels: changelog: non-user-facing

#579 Update travis matrix because of new WP version
  .travis.yml
Labels: changelog: non-user-facing

#595 Omit the price amount and currency meta for variable and grouped products.
  classes/presenters/woocommerce-product-price-amount-presenter.php
  classes/presenters/woocommerce-product-price-currency-presenter.php
  classes/woocommerce-utils.php
Labels: changelog: enhancement
