Repository Yoast/wpseo-woocommerce, pull requests merged in 2020-11, with the labels that each got.

#644 Removed the permalink watcher, because it is in Yoast SEO now
  classes/woocommerce-permalink-watcher.php
  classes/woocommerce-seo.php
  tests/classes/permalink-watcher-test.php
Labels: changelog: non-user-facing

#646 Composer: update YoastCS to v 2.1.0
  .travis.yml
  composer.json
  composer.lock
  tests/classes/schema-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#640 Fix grunt watch
  .travis.yml
  Gruntfile.js
  classes/index.php
  classes/presenters/index.php
  config/grunt/lib/version.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/shell.js
  config/grunt/task-config/watch.js
  config/grunt/task-config/webpack.js
  config/webpack/webpack.config.default.js
  config/webpack/webpack.config.dev.js
  config/webpack/webpack.config.prod.js
  js/src/assessments/ProductDescriptionAssessment.js
  js/src/yoastseo-woo-plugin.js
Labels: changelog: non-user-facing

#650 Update WC tested up to 4.7
  wpseo-woocommerce.php
Labels: changelog: non-user-facing

#651 Apply the wpseo_schema_product filter to make the Product type filterable
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#649 Composer: update BrainMonkey with dependencies
  composer.json
  composer.lock
  tests/classes/opengraph-test.php
  tests/classes/schema-test.php
  tests/classes/woocommerce-yoast-tab-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#653 QA: don't import namespaced functions
  tests/classes/schema-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#654 Unit Tests: make the testsuite compatible with PHPUnit 9 and test against PHP 8
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/TestCase.php
  tests/bootstrap.php
  tests/classes/opengraph-test.php
  tests/classes/presenters/pinterest-product-availability-presenter-test.php
  tests/classes/presenters/product-availability-presenter-test.php
  tests/classes/presenters/product-brand-presenter-test.php
  tests/classes/presenters/product-condition-presenter-test.php
  tests/classes/presenters/product-opengraph-deprecation-presenter-test.php
  tests/classes/presenters/product-price-amount-presenter-test.php
  tests/classes/presenters/product-price-currency-presenter-test.php
  tests/classes/presenters/product-retailer-item-id-presenter-test.php
  tests/classes/schema-test.php
  tests/classes/slack-test.php
  tests/classes/twitter-test.php
  tests/classes/woocommerce-dependencies-test.php
  tests/classes/woocommerce-yoast-tab-test.php
Labels: changelog: non-user-facing, yoast cs/qa
