Repository Yoast/wpseo-woocommerce, pull requests merged in 2021-05, with the labels that each got.

#681 CS/QA: various minor fixes
  classes/option-woo.php
  classes/woocommerce-permalink-watcher.php
  classes/woocommerce-seo.php
  config/composer/actions.php
  tests/classes/presenters/product-price-amount-presenter-test.php
  tests/classes/presenters/product-price-currency-presenter-test.php
  tests/classes/presenters/schema-presenter-test.php
  tests/classes/schema-test.php
  tests/classes/woocommerce-dependencies-test.php
  tests/classes/woocommerce-yoast-tab-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#682 Deploy changes
  .travis.yml
  scripts/deploy_to_dist.sh
Labels: changelog: non-user-facing

#683 P1 511 rating outputs disabling
  classes/woocommerce-seo.php
Labels: changelog: non-user-facing

#686 Merge language split feature branch
  .travis.yml
  js/src/assessments/ProductDescriptionAssessment.js
  scripts/deploy_to_dist.sh
Labels: changelog: non-user-facing

#687 Update filtering of the social images fallback.
  js/src/yoastseo-woo-plugin.js
Labels: changelog: non-user-facing

#690 LINGO-848 Update plugin version to 16.4
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: non-user-facing

#675 Update deprecated jQuery ready syntax
  classes/woocommerce-seo.php
Labels: community-patch
