Repository Yoast/wpseo-woocommerce, pull requests merged in 2021-12, with the labels that each got.

#730 Bump plugin grunt tasks 2.2.1
  yarn.lock
Labels: changelog: non-user-facing

#731 Composer: update dev dependencies
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#728 Prevent outputting empty product identifiers
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: bugfix

#732 Build js with latest version of yoastseo
  classes/woocommerce-dependencies.php
  composer.json
  composer.lock
  yarn.lock
Labels: changelog: other

#736 Composer: allow the PHPCS plugin
  .travis.yml
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing
