Repository Yoast/wpseo-woocommerce, pull requests merged in 2021-07, with the labels that each got.

#699 Do 434 zip test
  config/jenkins/Jenkinsfile_artifact
Labels: changelog: non-user-facing

#698 P2-1091 implement abstract indexable tag presenter
  .travis.yml
  classes/presenters/woocommerce-abstract-product-presenter.php
  classes/presenters/woocommerce-pinterest-product-availability-presenter.php
  classes/presenters/woocommerce-product-availability-presenter.php
  classes/presenters/woocommerce-product-brand-presenter.php
  classes/presenters/woocommerce-product-condition-presenter.php
  classes/presenters/woocommerce-product-price-amount-presenter.php
  classes/presenters/woocommerce-product-price-currency-presenter.php
  classes/presenters/woocommerce-product-retailer-item-id-presenter.php
  classes/woocommerce-dependencies.php
  classes/woocommerce-seo.php
  composer.json
  composer.lock
  tests/classes/presenters/pinterest-product-availability-presenter-test.php
  tests/classes/presenters/product-availability-presenter-test.php
  tests/classes/presenters/product-brand-presenter-test.php
  tests/classes/presenters/product-condition-presenter-test.php
  tests/classes/presenters/product-opengraph-deprecation-presenter-test.php
  tests/classes/presenters/product-price-amount-presenter-test.php
  tests/classes/presenters/product-price-currency-presenter-test.php
  tests/classes/presenters/product-retailer-item-id-presenter-test.php
  tests/classes/presenters/schema-presenter-test.php
  tests/classes/schema-test.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: enhancement

#701 Update grunt-plugin-tasks to 2.1.2
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#702 Set WP tested up to to 5.8 and WC tested up to to 5.5
  .travis.yml
  README.md
  wpseo-woocommerce.php
Labels: changelog: non-user-facing

#703 Add fallback when context is null and also fallback when product is null (also fixes: P2-1149)
  classes/woocommerce-seo.php
Labels: changelog: bugfix

#705 Cache product identifiers, make sure that they are always available.
  classes/woocommerce-seo.php
Labels: changelog: bugfix
