Repository Yoast/wpseo-woocommerce, pull requests merged in 2021-04, with the labels that each got.

#670 P1 345 woocommerce snippet in google preview
  classes/woocommerce-seo.php
  config/webpack/webpack.config.default.js
  js/src/yoastseo-woo-plugin.js
  package.json
  yarn.lock
Labels: changelog: enhancement

#671 P3-464 Fix product price schema output
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#674 Adapt import from yoastseo
  js/src/assessments/ProductDescriptionAssessment.js
Labels: changelog: non-user-facing

#669 Add product gallery image as fallback for social previews
  js/src/yoastseo-woo-plugin.js
Labels: changelog: enhancement

#678 Composer: update dev dependencies
  composer.json
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#677 P1-488 Shoppingdata Availability typography
  classes/woocommerce-seo.php
Labels: changelog: non-user-facing

#679 Output a product gallery image before defaulting to the site-wide social default
  js/src/yoastseo-woo-plugin.js
Labels: changelog: non-user-facing
