Repository Yoast/wpseo-woocommerce, pull requests merged in 2021-08, with the labels that each got.

#704 Exclude wordpress-seo from vendor directory when developing.
  .travis.yml
  composer.json
  composer.lock
  config/grunt/task-config/makepot.js
  languages/yoast-woo-seo.pot
  tests/bootstrap.php
Labels: changelog: non-user-facing

#710 Do not exclude wordpress-seo from classmap anymore.
  .travis.yml
  composer.json
  languages/yoast-woo-seo.pot
  tests/bootstrap.php
Labels: changelog: non-user-facing

#709 Set custom assessors on product pages
  js/src/initializers/product-assessor.js
  js/src/yoastseo-woo-worker.js
  package.json
  yarn.lock
Labels: changelog: enhancement

#712 add missing dependencies
  languages/yoast-woo-seo.pot
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#713 Up the required Yoast SEO version
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#716 Exclude videos in Images assessment in Woo product pages
  js/src/initializers/product-assessor.js
Labels: changelog: non-user-facing
