Repository Yoast/wpseo-woocommerce, pull requests merged in 2021-01, with the labels that each got.

#661 Added schema presenter.
  classes/presenters/woocommerce-schema-presenter.php
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
  yarn.lock
Labels: changelog: bugfix

#662 Added unit tests for WooCommerce schema presenter.
  tests/classes/presenters/schema-presenter-test.php
Labels: changelog: non-user-facing

#663 Replace the security checker
  .travis.yml
Labels: changelog: non-user-facing, tooling
