Repository Yoast/wpseo-woocommerce, pull requests merged in 2022-07, with the labels that each got.

#789 Send data to worker on various variation manipulations
  classes/woocommerce-seo.php
  config/webpack/webpack.config.default.js
  js/src/initializers/product-assessor.js
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#791 Send SKU data to worker on various variation manipulations
  classes/woocommerce-seo.php
  js/src/initializers/product-assessor.js
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: enhancement

#792 Set minimum WP version to 5.9
  .github/workflows/integrationtest.yml
  README.md
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other
