Repository Yoast/wpseo-woocommerce, pull requests merged in 2022-01, with the labels that each got.

#738 Travis: remove "fix PHP 8.0 build icm Composer 2.2"
  .travis.yml
Labels: yoast cs/qa, changelog: non-user-facing

#737 Made configuration for product description length adaptable
  js/src/assessments/ProductDescriptionAssessment.js
  js/tests/assessments/ProductDescriptionAssessment.test.js
Labels: changelog: enhancement

#741 Set tested up to WC to 6.1 and WP to 5.9
  .travis.yml
  README.md
  wpseo-woocommerce.php
Labels: changelog: other

#742 Bump minimum required Free version to 18.0
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#740 CI: switch to GitHub Actions
  .gitattributes
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/integrationtest.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/security.yml
  .github/workflows/unittest.yml
  .phpcs.xml.dist
  .travis.yml
  composer.json
  composer.lock
  config/grunt/task-config/shell.js
  config/scripts/install-wp-tests.sh
  deploy_keys/wpseo_woo_deploy.enc
  scripts/deploy_to_dist.sh
Labels: yoast cs/qa, changelog: non-user-facing

#747 Run integration tests with WP 5.9
  .github/workflows/integrationtest.yml
Labels: changelog: non-user-facing
