Repository Yoast/wpseo-woocommerce, pull requests merged in 2022-03, with the labels that each got.

#750 Improve schema on product and checkout pages
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#754 Set minimum WP version to 5.8 and tested up to to 5.9
  .github/workflows/integrationtest.yml
  README.md
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#755 DUPP-318 Bump minimum required Free version to 18.4-RC0
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#756 GH Actions: minor updates
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/integrationtest.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/security.yml
  .github/workflows/unittest.yml
Labels: yoast cs/qa, changelog: non-user-facing

#759 Schema output for Product is not correct and contains Unspecified Type
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: other
