Repository Yoast/wpseo-woocommerce, pull requests merged in 2022-09, with the labels that each got.

#816 Remove all deprecated PHP before 14.4
  classes/presenters/woocommerce-product-opengraph-deprecation-presenter.php
  classes/woocommerce-opengraph.php
  classes/woocommerce-permalink-watcher.php
  classes/woocommerce-seo.php
  tests/classes/presenters/product-opengraph-deprecation-presenter-test.php
Labels: changelog: non-user-facing

#826 Set minimum Free version to 19.7
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#822 PC-495 - Cache product identifier and SKU data of product variants
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#827 Check whether product identifiers can be retrieved
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#828 edit feedback strings for SKU and PI assessment
  js/src/initializers/product-assessor.js
Labels: changelog: non-user-facing

#830 Improve Offers / priceSpecification output
  classes/option-woo.php
  classes/woocommerce-schema.php
  classes/woocommerce-seo.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#831 PC-613-product-identifier-feedback-only-updates-when-you-click-on-the-page
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#832 PC-626 Fix the `color` and `pattern` output
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: bugfix

#835 Add material to schema data output
  classes/option-woo.php
  classes/woocommerce-schema.php
  classes/woocommerce-seo.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#836 Prepare renaming master to main
  .github/workflows/cs.yml
  .github/workflows/integrationtest.yml
  .github/workflows/js.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: changelog: non-user-facing
