Repository Yoast/wpseo-woocommerce, pull requests merged in 2022-08, with the labels that each got.

#794 Bumps minimum WP version to 5.9
  .github/workflows/integrationtest.yml
  README.md
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#795 bumps Yoast SEO to 19.5
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#796 Composer: update PHPCS
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#797 GH Actions: minor tweaks
  .github/workflows/deploy.yml
Labels: yoast cs/qa, changelog: non-user-facing

#798 CS/QA: various minor CS fixes
  classes/woocommerce-yoast-ids.php
  tests/classes/woocommerce-yoast-ids-test.php
  tests/doubles/ids-double.php
Labels: yoast cs/qa, changelog: non-user-facing

#800 GH Actions/test: clean up script after dropping support for WP 5.9
  .github/workflows/integrationtest.yml
Labels: yoast cs/qa, changelog: non-user-facing

#799 QA: fix incorrect attribute escapes
  classes/woocommerce-yoast-ids.php
  classes/woocommerce-yoast-tab.php
Labels: yoast cs/qa, changelog: bugfix

#801 Refactors code that sends over SKU and product identifier data to the analysis
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#802 Add dependabot configuration file
  .github/dependabot.yml
Labels: yoast cs/qa, changelog: non-user-facing

#804 fix typos in element names
  js/src/yoastseo-woo-identifiers.js
  js/src/yoastseo-woo-replacevars.js
Labels: changelog: non-user-facing

#806 PC-385 - Listen for price changes of simple products and send that over to the analysis.
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#807 Listen for changes to the product variations tab before adding the va…
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#809 Bump minimim required version to 19.6
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#810 Set the minimum required version to the latest RC
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: non-user-facing

#813 Add support for ASIN product identifier.
  classes/woocommerce-schema.php
  classes/woocommerce-seo.php
  classes/woocommerce-yoast-ids.php
  classes/woocommerce-yoast-tab.php
  js/src/yoastseo-woo-replacevars.js
  tests/classes/schema-test.php
Labels: changelog: enhancement, UI change

#815 Fix the assessment results for SKU and product identifier not always updating for variable products
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#817 Revert "Add support for ASIN product identifier."
  README.md
  classes/woocommerce-schema.php
  classes/woocommerce-seo.php
  classes/woocommerce-yoast-ids.php
  classes/woocommerce-yoast-tab.php
  js/src/yoastseo-woo-replacevars.js
  tests/classes/schema-test.php
Labels: changelog: non-user-facing

#814 PC-191 Add shortlinks for Title assessment
  js/src/initializers/product-assessor.js
Labels: changelog: non-user-facing

#819 Make product identifiers and SKU assessments independent of price
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#820 Check whether we can retrieve SKU and add the information to custom data
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#821 Check whether variant SKUs can be detected
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#823 Fix SKU assessment not updating when variants are deleted after opening a saved product
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#824 PC 510 Remove feedback with a green bullet for spaces in SKU and product identifiers
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing

#825 Fix SKU and product identifier assessments not showing up on a new product without variants
  js/src/yoastseo-woo-identifiers.js
Labels: changelog: non-user-facing
