Repository Yoast/wpseo-woocommerce, pull requests merged in 2022-06, with the labels that each got.

#773 DUPP-389 - DUPP-389-add-variation-global-ids-to-schema
  classes/woocommerce-schema.php
  classes/woocommerce-yoast-ids.php
  tests/classes/schema-test.php
  tests/classes/woocommerce-yoast-ids-test.php
Labels: changelog: enhancement

#774 Bump minimum required free version
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#775 DUPP-401 - DUPP-401-add-variations-sku-and-url-to-schema
  classes/woocommerce-schema.php
  composer.json
  composer.lock
  tests/classes/schema-test.php
Labels: community-patch, changelog: enhancement

#776 Don't output dates on ItemPage
  classes/woocommerce-schema.php
  composer.lock
Labels: changelog: enhancement

#777 Sets minimum WordPress version back to 5.8
  .github/workflows/integrationtest.yml
  README.md
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: non-user-facing

#779 Update Schema to follow the new best-practice for the @id of the WebPage piece
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
  tests/mocks/schema-ids.php
Labels: changelog: enhancement

#782 PC-33 Add word complexity assessment for English
  js/src/initializers/product-assessor.js
Labels: changelog: enhancement

#783 edit typo in variants identifier name
  classes/woocommerce-yoast-ids.php
  tests/classes/woocommerce-yoast-ids-test.php
Labels: changelog: other

#785 Bump minimum required Free version to 19.3
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other
