Repository Yoast/wpseo-woocommerce, pull requests merged in 2022-11, with the labels that each got.

#842 Composer: update dev dependencies
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#843 Gh Actions: various tweaks
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/integrationtest.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: yoast cs/qa, changelog: non-user-facing

#844 PHP 8.2 | Tests: fix some dynamic property creation errors in the tests
  tests/classes/slack-test.php
  tests/classes/twitter-test.php
  tests/classes/woocommerce-yoast-ids-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#846 Update changelog format (both in file and creation settings)
  README.md
  config/grunt/task-config/update-changelog-to-latest.js
Labels: changelog: non-user-facing

#848 Composer: update test utilities
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#849 Composer: update test utilities (round 2)
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#852 Remove unneeded dependency
  classes/woocommerce-seo.php
  composer.json
  composer.lock
Labels: changelog: enhancement

#854 bump the required free version to 19.12
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other
