Repository Yoast/wpseo-woocommerce, pull requests merged in 2023-01, with the labels that each got.

#863 update plugin-grunt-tasks to 2.4 and update date format in readme.md
  README.md
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#867 Composer: update YoastCS and dependencies
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#870 Fix the Schema for Product prices with and without taxes
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: enhancement

#871 Bump minimum Free version to 19.14
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#874 Never use the link table when looking for the placeholder image in Woo products
  classes/woocommerce-schema.php
  tests/classes/schema-test.php
Labels: changelog: other

#866 fix breadcrumb link
  classes/woocommerce-seo.php
Labels: changelog: other
