Repository Yoast/wpseo-woocommerce, pull requests merged in 2023-11, with the labels that each got.

#946 Tests/Unit: use PSR-4
  .phpcs.xml.dist
  composer.json
  phpunit.xml.dist
  tests/Unit/Classes/Dependencies_Test.php
  tests/Unit/Classes/Integrations/TranslationsPress_Test.php
  tests/Unit/Classes/OpenGraph_Test.php
  tests/Unit/Classes/Presenters/Pinterest_Product_Availability_Presenter_Test.php
  tests/Unit/Classes/Presenters/Product_Availability_Presenter_Test.php
  tests/Unit/Classes/Presenters/Product_Brand_Presenter_Test.php
  tests/Unit/Classes/Presenters/Product_Condition_Presenter_Test.php
  tests/Unit/Classes/Presenters/Product_Price_Amount_Presenter_Test.php
  tests/Unit/Classes/Presenters/Product_Price_Currency_Presenter_Test.php
  tests/Unit/Classes/Presenters/Product_Retailer_Item_ID_Presenter_Test.php
  tests/Unit/Classes/Presenters/Schema_Presenter_Test.php
  tests/Unit/Classes/Schema_Test.php
  tests/Unit/Classes/Slack_Test.php
  tests/Unit/Classes/Twitter_Test.php
  tests/Unit/Classes/Utils_Test.php
  tests/Unit/Classes/Yoast_Ids_Test.php
  tests/Unit/Classes/Yoast_Tab_Test.php
  tests/Unit/Doubles/Dependencies_Double.php
  tests/Unit/Doubles/Schema_Double.php
  tests/Unit/Doubles/Schema_IDs_Mock.php
  tests/Unit/Doubles/Yoast_Ids_Double.php
  tests/Unit/Doubles/Yoast_Tab_Double.php
  tests/Unit/TestCase.php
  tests/Unit/bootstrap.php
  tests/bootstrap.php
  tests/classes/seo-trait.php
Labels: yoast cs/qa, changelog: non-user-facing

#947 Tests/WP: use PSR-4
  .gitattributes
  .github/workflows/test.yml
  .gitignore
  .phpcs.xml.dist
  composer.json
  integration-tests/framework/woocommerce-unittestcase.php
  phpunit-wp.xml.dist
  tests/WP/Classes/Option_Woo_Test.php
  tests/WP/Doubles/Option_Woo_Double.php
  tests/WP/Doubles/WooCommerce_SEO_Double.php
  tests/WP/TestCase.php
  tests/WP/WooCommerce_SEO_Test.php
  tests/WP/bootstrap.php
Labels: yoast cs/qa, changelog: non-user-facing

#948 GH Actions: enable linting and testing against PHP 8.3
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: yoast cs/qa, changelog: other

#949 Tests: make dataproviders `static`
  tests/Unit/Classes/Integrations/TranslationsPress_Test.php
  tests/Unit/Classes/Yoast_Ids_Test.php
  tests/Unit/Classes/Yoast_Tab_Test.php
  tests/WP/Classes/Option_Woo_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#945 438 import global identifier values such as gtin isbn mpn etc into the woocommerce seo plugin fields
  classes/woocommerce-import-export.php
  classes/woocommerce-seo.php
  tests/Unit/Classes/Import_Export_Test.php
Labels: changelog: enhancement, UI change

#951 Composer.json: add link to security policy
  composer.json
Labels: yoast cs/qa, changelog: other

#952 GH Actions: switch to Coveralls action runner to upload reports
  .github/workflows/test.yml
Labels: yoast cs/qa, changelog: non-user-facing

#953 GH Actions: update a few links in inline comments
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: yoast cs/qa, changelog: non-user-facing

#961 Extend the global identifier import/export feature to variations
  classes/woocommerce-import-export.php
  tests/Unit/Classes/Import_Export_Test.php
Labels: changelog: non-user-facing, fix before release
