Repository Yoast/wpseo-woocommerce, pull requests merged in 2023-09, with the labels that each got.

#933 Use Translationspress instead of pulling translations at build time from translate.yoast.com
  Gruntfile.js
  classes/integrations/woocommerce-translationspress.php
  classes/woocommerce-seo.php
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/glotpress_download.js
  config/grunt/task-config/makepot.js
  config/grunt/task-config/shell.js
  config/webpack/webpack.config.default.js
  languages/index.php
  languages/yoast-woo-seo-ar.mo
  languages/yoast-woo-seo-ca.mo
  languages/yoast-woo-seo-cs_CZ.mo
  languages/yoast-woo-seo-da_DK.mo
  languages/yoast-woo-seo-de_DE.mo
  languages/yoast-woo-seo-el.mo
  languages/yoast-woo-seo-en_AU.mo
  languages/yoast-woo-seo-en_GB.mo
  languages/yoast-woo-seo-en_NZ.mo
  languages/yoast-woo-seo-es_ES.mo
  languages/yoast-woo-seo-es_MX.mo
  languages/yoast-woo-seo-fa_IR.mo
  languages/yoast-woo-seo-fi.mo
  languages/yoast-woo-seo-fr_FR.mo
  languages/yoast-woo-seo-he_IL.mo
  languages/yoast-woo-seo-hi_IN.mo
  languages/yoast-woo-seo-id_ID.mo
  languages/yoast-woo-seo-it_IT.mo
  languages/yoast-woo-seo-ja.mo
  languages/yoast-woo-seo-nb_NO.mo
  languages/yoast-woo-seo-nl_BE.mo
  languages/yoast-woo-seo-nl_NL.mo
  languages/yoast-woo-seo-pl_PL.mo
  languages/yoast-woo-seo-pt_BR.mo
  languages/yoast-woo-seo-pt_PT.mo
  languages/yoast-woo-seo-ro_RO.mo
  languages/yoast-woo-seo-ru_RU.mo
  languages/yoast-woo-seo-sr_RS.mo
  languages/yoast-woo-seo-sv_SE.mo
  languages/yoast-woo-seo-tr_TR.mo
  languages/yoast-woo-seo-uk.mo
  languages/yoast-woo-seo-vi.mo
  languages/yoast-woo-seo.pot
  package.json
  tests/classes/integrations/woocommerce-translationspress-test.php
  yarn.lock
Labels: changelog: enhancement

#935 .gitattributes: minor clean up
  .gitattributes
Labels: yoast cs/qa, changelog: non-user-facing

#936 Composer: normalize the file, add script descriptions
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#937 PHPUnit config: update schema reference
  phpunit-integration.xml.dist
  phpunit.xml.dist
Labels: yoast cs/qa, changelog: non-user-facing

#938 Composer: allow composer installers 2.x
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: other

#939 Composer/Tests: update test dependencies
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing
