Repository Yoast/wpseo-woocommerce, pull requests merged in 2023-04, with the labels that each got.

#894 Merges the restructuring yoastseo project
  config/webpack/webpack.config.default.js
  config/webpack/webpack.config.prod.js
  js/src/initializers/product-assessor.js
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#896 Bump minimum required Free version to 20.6
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#900 Bump minimum required version to 20.6 (again)
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#901 Adds functionality to gather translation strings from yoastseo via webpack
  Gruntfile.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/makepot.js
  config/grunt/task-config/shell.js
  config/webpack/webpack.config.default.js
  languages/yoast-woo-seo.pot
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#898 Prevents an error when the short description metabox is not present
  js/src/yoastseo-woo-replacevars.js
Labels: changelog: bugfix

#902 Set the minimum supported WordPress version to 6.1
  .github/workflows/integrationtest.yml
  README.md
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other
