Repository Yoast/wpseo-woocommerce, pull requests merged in 2023-07, with the labels that each got.

#920 Prevent replacing Woo breadcrumbs if using the blockified template
  classes/woocommerce-seo.php
Labels: changelog: enhancement

#922 Add new copy to let users know about the Woo 7.9.0 limitation
  classes/woocommerce-seo.php
Labels: changelog: non-user-facing, UI change

#921 Merges the feature branch into trunk
  classes/woocommerce-seo.php
  js/src/initializers/input-focus.js
  js/src/initializers/input-focus/helpers.js
  js/src/initializers/input-focus/simple-product.js
  js/src/initializers/input-focus/variable-product.js
  js/src/initializers/product-assessor.js
  js/src/initializers/woo-identifiers.js
  js/src/yoastseo-woo-identifiers.js
  js/src/yoastseo-woo-plugin.js
  js/src/yoastseo-woo-worker.js
  js/tests/initializers/input-focus.test.js
  js/tests/initializers/input-focus/simple-product.test.js
  js/tests/initializers/input-focus/variable-product.test.js
  package.json
Labels: changelog: non-user-facing

#923 Bump minimum required free version to 20.12
  classes/woocommerce-dependencies.php
  tests/classes/woocommerce-dependencies-test.php
Labels: changelog: other

#925 870 fix actionable buttons for variation product without variations
  js/src/initializers/input-focus.js
  js/tests/initializers/input-focus.test.js
Labels: changelog: non-user-facing

#928 Sets the WordPress tested up to version to 6.3.
  README.md
Labels: changelog: other
